---
title: 'Universidade: reprodução ou emancipação?'
author: | 
  | CTIA67 - ESTUDOS SOBRE A CONTEMPORANEIDADE I (ICTI/UFBA)
  | Leonardo F. Nascimento
date: "23/08/2021"
output: beamer_presentation
---

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

##  "Não há um racismo, mas vários racismos..."

- há tantos racismos quantos grupos que precisem justificar sua existência como tal, o que constitui a função invariante dos racismos.


## O racismo da inteligência


- "O racismo da inteligência é um racismo da classe dominante"

<br>

- A reprodução social desta classe dominte "depende em parte da transmissão do capital cultural"


## O que é capital cultural?

- O que você sabe?

## O que é capital cultural?

- Incorporado: habilidades, sotaque, jeitos, postura, gestos, gosto, modos de falar, domínio de idiomas...

<br>

- Objetificado: livros, obras de arte, instrumentos musicais... 

<br>

- Institucionalizado: títulos escolares, diplomas, mestrado/doutorado...



## O que é capital cultural?


- Quando você compartilha o capital cultural em uma comunidade, você tem a sensação de uma identidade coletiva..

<br>

- Crenças, jeitos, maneiras, valores, etc.

## Capital social


- Quem você conhece?

<br>

- Networking, relações com pessoas ricas, poderosas, inteligentes, "bem posicionadas"...

<br>

- "filho de...", "irmão de...", "neto de..."

## "teodicéia de seu próprio privilégio"

- "os dominadores em toda e qualquer sociedade (precisam) sentir justificados de sua existência como dominantes";

<br>

- "eles (precisam) sentir como possuindo uma essência superior

# "Todo racismo é um essencialismo"


## Racismo da inteligência 

- "poder que repousa em parte sobre a posse de títulos escolares que são considerados como uma garantia de inteligência" (são como os antigos títulos de nobreza)


## Classificação escolar 

> "A classificação escolar é uma classificação social eufemizada, portanto naturalizada, absolutizada, uma classificação social que já sofreu uma censura, portanto uma alquimia, uma transformação tendendo a transformar as diferenças de classe em diferenças de "inteligência", de "dom", isto é, em diferenças de natureza"